version: "3"
services:
  redis:
    image: "redis:latest"
    container_name: my_redis
    ports:
      - "6379:6379"
    networks: 
      - calendar-net

  concert_calendar:
    image: "${DOCKERHUB_USERNAME}/${PROJECT_NAME}"
    container_name: my_calendar
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks: 
      - calendar-net
networks:
        calendar-net:
                external: true
